version: "3.9"
services:
  native-builder:
    image: softinstigate/graalvm-maven
    container_name: graalvm-builder
    build:
      context: .
    volumes:
      - ".:/opt/app"
      - "$HOME/.m2:/root/.m2"
    profiles: ["native-image"]
    command: "clean package -Pnative-image"
  native-runner:
    container_name: function-sample-aws-native
    depends_on:
      native-builder:
        condition: service_completed_successfully
    links:
      - native-builder
    build:
      context: docker/native
    ports:
     - "9000:8080"
    profiles:
     - "native-image"
  java-runner:
    container_name: function-sample-aws
    build:
      context: docker/java
    ports:
      - "9000:8080"

